DATASET:
  imgMaxSize: 400
  imgSizes: (300, 375, 450, 525, 600)
  list_test: ./data/demo.odgt
  list_train: ./data/hot_train.odgt
  list_val: ./data/hot_val.odgt
  num_class: 18
  padding_constant: 8
  random_flip: True
  root_dataset: E:/dataset
  segm_downsampling_rate: 8
DIR: ckpt/hot-c1
MODEL:
  arch_decoder: c1
  arch_encoder: resnet50dilated
  fc_dim: 2048
  weights_decoder: 
  weights_encoder: 
  with_part: True
TEST:
  batch_size: 8
  checkpoint: epoch_14.pth
  result: ./
  visualize: True
TRAIN:
  batch_size_per_gpu: 4
  beta1: 0.9
  deep_sup_scale: 0.4
  disp_iter: 20
  epoch_iters: 100
  fix_bn: False
  lr_decoder: 0.02
  lr_encoder: 0.02
  lr_pow: 0.9
  num_epoch: 10
  optim: SGD
  seed: 304
  start_epoch: 0
  weight_decay: 0.0001
  workers: 2
VAL:
  batch_size: 1
  checkpoint: epoch_10.pth